### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/interval-quiz#1]
In the following, X, Y, and Z random.

- [X] X is the Y of Z.
    - E.g.: C is the 4th of G.
- [ ] What chords can be played when X is the melody and Y is the bass note.
    - E.g.: What chords can be played when C is the melody and E is the bass note.
- [ ] What chord qualities can be played with scale degree X as the melody.
    - E.g. Major, minor, dominant, alerted, diminished, half diminished.
- [ ] #2
